<?php 
$plugin = array();
$plugin['name']             = 'Google Login';      
$plugin['code']             = 'google';
$plugin['version']          = '1.0';
$plugin['description']      = 'Used by millions, Akismet is quite possibly the best way in the world to protect your blog from comment and trackback spam. It keeps your site protected from spam even while you sleep. To get started: 1) Click the "Activate" link to the left of this description, 2) Sign up for an Akismet API key, and 3) Go to your Akismet configuration page, and save your API key.';
$plugin['author']['name']   = 'Ano Van';
$plugin['author']['link']   = 'http://anovan.com';
$plugin['author']['email']  = 'ano@linkit360.com';
